BEGIN;

DROP TABLE Animal CASCADE;
DROP TABLE People CASCADE;
DROP TABLE Animal_actor CASCADE;
DROP TABLE Attention CASCADE;
DROP TABLE Item CASCADE;
DROP TYPE place CASCADE;
DROP TABLE Scene CASCADE;
DROP TABLE Emotion CASCADE;
DROP TABLE Feelings CASCADE;
DROP TABLE History CASCADE;
DROP TABLE ACTION CASCADE;

COMMIT;