BEGIN;

DROP TABLE IF EXISTS  Actors CASCADE;
DROP TABLE IF EXISTS  Animal CASCADE;
DROP TABLE IF EXISTS  People CASCADE;
DROP TABLE IF EXISTS  Attention CASCADE;
DROP TABLE IF EXISTS  Item CASCADE;
DROP TYPE IF EXISTS place CASCADE;
DROP TABLE IF EXISTS  Scene CASCADE;
DROP TABLE IF EXISTS  Emotion CASCADE;
DROP TABLE IF EXISTS  Feelings CASCADE;
DROP TABLE IF EXISTS  History CASCADE;
DROP TABLE IF EXISTS  Action CASCADE;

COMMIT;